name: Ubuntu

on: [push]

jobs:
  bionic:
    runs-on: ubuntu-latest
    name: Ubuntu Bionic
    strategy:
      matrix:
        packages:
          - "libopensplice69"
steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Build and push
    id: docker_build
    uses: docker/build-push-action@v2
    with:
      push: false
      file: bionic/Dockerfile.${{ matrix.name }}
      tags: generator:latest
